In [2]:
import numpy as np

In [3]:
A=np.random.randint(10,size=(5,5))
B=np.random.randint(10,size=(5,5))

In [4]:
A,B

(array([[5, 4, 2, 9, 8],
        [9, 3, 6, 9, 2],
        [3, 6, 9, 6, 2],
        [1, 7, 8, 4, 7],
        [1, 6, 5, 8, 7]]),
 array([[3, 4, 7, 3, 0],
        [8, 2, 7, 7, 6],
        [2, 2, 9, 4, 0],
        [6, 4, 0, 3, 0],
        [9, 0, 6, 2, 2]]))

In [5]:
A+B

array([[ 8,  8,  9, 12,  8],
       [17,  5, 13, 16,  8],
       [ 5,  8, 18, 10,  2],
       [ 7, 11,  8,  7,  7],
       [10,  6, 11, 10,  9]])

In [6]:
np.dot(A,B)

array([[177,  68, 129,  94,  40],
       [135,  90, 150, 103,  22],
       [129,  66, 156, 109,  40],
       [162,  50, 170, 110,  56],
       [172,  58, 136, 103,  50]])

In [7]:
np.mean(A,axis=1)

array([5.6, 5.8, 5.2, 5.4, 5.4])

In [8]:
np.std(A,axis=1)

array([2.57681975, 2.92574777, 2.48193473, 2.57681975, 2.41660919])

In [9]:
np.mean(B,axis=1)

array([3.4, 6. , 3.4, 2.6, 3.8])

In [10]:
np.std(B,axis=1)

array([2.24499443, 2.0976177 , 3.0724583 , 2.33238076, 3.24961536])